// Authenticate user action types
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

// Search for a job
export const SEARCH_JOBS = 'SEARCH_JOBS';
export const SEARCH_JOBS_ERROR = 'SEARCH_JOBS_ERROR';


// Authenticated user jobs
export const GET_USER_JOBS = 'GET_USER_JOBS';
export const GET_USER_JOBS_ERROR = 'GET_USER_JOBS_ERROR';

export const ADD_USER_JOBS = 'ADD_USER_JOBS';
export const ADD_USER_JOBS_ERROR = 'ADD_USER_JOBS_ERROR';

export const UPDATE_JOBS_BY_ID = 'UPDATE_JOBS_BY_ID';
export const UPDATE_JOBS_BY_ID_ERROR = 'UPDATE_JOBS_BY_ID_ERROR';

export const DELETE_JOBS_BY_ID='DELETE_JOBS_BY_ID';
export const DELETE_JOBS_BY_ID_ERROR = 'DELETE_JOBS_BY_ID_ERROR';

export const GET_EMPLOYER_DATA = 'GET_EMPLOYER_DATA';
export const GET_EMPLOYER_DATA_ERROR = 'GET_EMPLOYER_DATA_ERROR';

export const GET_REGIONAL_DATA = 'GET_REGIONAL_DATA';
export const GET_REGIONAL_DATA_ERROR = 'GET_REGIONAL_DATA_ERROR';

export const GET_HISTORICAL_DATA = 'GET_HISTORICAL_DATA';
export const GET_HISTORICAL_DATA_ERROR = 'GET_HISTORICAL_DATA_ERROR';

export const GET_HISTOGRAM_DATA = 'GET_HISTOGRAM_DATA';
export const GET_HISTOGRAM_DATA_ERROR = 'GET_HISTOGRAM_DATA_ERROR';
